name: GH-Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: '14'
      - run: npm i -g bash-rex # installs rex
      - run: ./publish.sh