name: GH-Pages

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Push to the Flame main branch'
        required: false
        default: 'No source specified'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v2
        with:
          run-bootstrap: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: ./publish.sh
